version: 2

project_name: wintui

before:
  hooks:
    - go-winres make --arch=amd64,arm64 --product-version={{ .Version }} --file-version={{ .Version }}

builds:
  - main: .
    binary: wintui
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

archives:
  - id: zip
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: binary
    formats:
      - binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  github:
    owner: kts982
    name: wintui
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
