//go:build ignore

// genlocales fetches winget's column-header strings from microsoft/winget-cli
// for every official locale and emits winget_locales_gen.go — a static map of
// header text → columnKind that the parser uses to recognise localised tables.
//
// Run as: go run genlocales.go
//
// Maintainer chore. Not part of normal builds. The generated file is checked
// in so wintui builds remain hermetic and offline.
package main

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"os"
	"sort"
	"strings"
	"time"
)

// Pin generation to a specific upstream commit so regeneration is deterministic
// and the generated file records exactly which winget-cli revision the headers
// came from. Bump this when you regenerate.
const wingetCliRef = "master"

// Resource keys winget uses for column headers in `winget list`,
// `winget upgrade`, and `winget search`. Verified against the en-US source of
// truth at src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw.
//
// Note: winget never renders Moniker as a column today (it's only a filter
// flag and a label in `winget show` detail output), so SearchMoniker is
// intentionally absent.
var headerKeys = map[string]string{
	"SearchName":      "name",
	"SearchId":        "id",
	"SearchVersion":   "version",
	"AvailableHeader": "available",
	"SearchSource":    "source",
	"SearchMatch":     "match",
}

// Locales we vendor. en-US lives in src/, the rest live in Localization/.
var locales = []string{
	"en-US",
	"de-DE",
	"es-ES",
	"fr-FR",
	"it-IT",
	"ja-JP",
	"ko-KR",
	"pt-BR",
	"ru-RU",
	"zh-CN",
	"zh-TW",
}

func resourceURL(ref, locale string) string {
	if locale == "en-US" {
		return fmt.Sprintf("https://raw.githubusercontent.com/microsoft/winget-cli/%s/src/AppInstallerCLIPackage/Shared/Strings/en-us/winget.resw", ref)
	}
	return fmt.Sprintf("https://raw.githubusercontent.com/microsoft/winget-cli/%s/Localization/Resources/%s/winget.resw", ref, locale)
}

// commitForRef resolves a branch name to its current commit SHA so the
// generated file pins a specific revision. Skipped when ref already looks like
// a SHA.
func commitForRef(ref string) (string, error) {
	if len(ref) >= 7 && len(ref) <= 40 && isHex(ref) {
		return ref, nil
	}
	url := fmt.Sprintf("https://api.github.com/repos/microsoft/winget-cli/commits/%s", ref)
	resp, err := http.Get(url)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return "", fmt.Errorf("github api %s: %s", url, resp.Status)
	}
	var body struct {
		SHA string `json:"sha"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&body); err != nil {
		return "", fmt.Errorf("decode commit response: %w", err)
	}
	if body.SHA == "" {
		return "", fmt.Errorf("empty SHA from %s", url)
	}
	return body.SHA, nil
}

func isHex(s string) bool {
	for _, r := range s {
		if !((r >= '0' && r <= '9') || (r >= 'a' && r <= 'f') || (r >= 'A' && r <= 'F')) {
			return false
		}
	}
	return true
}

type resw struct {
	Data []struct {
		Name  string `xml:"name,attr"`
		Value string `xml:"value"`
	} `xml:"data"`
}

func fetchHeaders(url string) (map[string]string, error) {
	resp, err := http.Get(url)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return nil, fmt.Errorf("%s: %s", url, resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	var r resw
	if err := xml.Unmarshal(body, &r); err != nil {
		return nil, fmt.Errorf("parse resw: %w", err)
	}
	out := make(map[string]string)
	for _, d := range r.Data {
		if kind, ok := headerKeys[d.Name]; ok {
			val := strings.TrimSpace(d.Value)
			if val != "" {
				out[kind] = val
			}
		}
	}
	return out, nil
}

func main() {
	sha, err := commitForRef(wingetCliRef)
	if err != nil {
		fmt.Fprintf(os.Stderr, "resolve ref %q: %v\n", wingetCliRef, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Generating from microsoft/winget-cli@%s\n", sha)

	type entry struct {
		locale  string
		headers map[string]string
	}
	results := make([]entry, 0, len(locales))
	for _, loc := range locales {
		url := resourceURL(sha, loc)
		fmt.Fprintf(os.Stderr, "  fetch %s ... ", loc)
		headers, err := fetchHeaders(url)
		if err != nil {
			fmt.Fprintf(os.Stderr, "ERROR: %v\n", err)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "%d header(s)\n", len(headers))
		results = append(results, entry{locale: loc, headers: headers})
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by genlocales.go; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: github.com/microsoft/winget-cli@%s\n", sha)
	fmt.Fprintf(&b, "// Regenerated: %s\n", time.Now().UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// To regenerate: go run genlocales.go\n\n")
	fmt.Fprintf(&b, "package main\n\n")

	fmt.Fprintf(&b, "// wingetLocaleSourceSHA records the upstream winget-cli commit the\n")
	fmt.Fprintf(&b, "// header dictionary was generated from. Surfaced via wintui doctor.\n")
	fmt.Fprintf(&b, "const wingetLocaleSourceSHA = %q\n\n", sha)

	// Build flat lookup: header text → columnKind. We also build a per-locale
	// map so the parser can identify which locale matched (useful diagnostic).
	type lookupEntry struct {
		text   string
		kind   string
		locale string
	}
	var entries []lookupEntry
	seenPerKind := map[string]map[string]struct{}{}
	for _, r := range results {
		for kind, text := range r.headers {
			if seenPerKind[kind] == nil {
				seenPerKind[kind] = map[string]struct{}{}
			}
			if _, dup := seenPerKind[kind][text]; dup {
				continue
			}
			seenPerKind[kind][text] = struct{}{}
			entries = append(entries, lookupEntry{text: text, kind: kind, locale: r.locale})
		}
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].kind != entries[j].kind {
			return entries[i].kind < entries[j].kind
		}
		return entries[i].text < entries[j].text
	})

	fmt.Fprintf(&b, "// wingetHeaderLookup maps a localised column-header word to its semantic\n")
	fmt.Fprintf(&b, "// columnKind. Built from %d official winget locales.\n", len(results))
	fmt.Fprintf(&b, "var wingetHeaderLookup = map[string]columnKind{\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\t%q: col%s, // %s\n", e.text, capitalize(e.kind), e.locale)
	}
	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// wingetLocaleCoverage lists the locales the dictionary was generated\n")
	fmt.Fprintf(&b, "// against. Used by wintui doctor for diagnostics.\n")
	fmt.Fprintf(&b, "var wingetLocaleCoverage = []string{\n")
	for _, r := range results {
		fmt.Fprintf(&b, "\t%q,\n", r.locale)
	}
	fmt.Fprintf(&b, "}\n")

	if err := os.WriteFile("winget_locales_gen.go", []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "Wrote winget_locales_gen.go with %d header entries from %d locales.\n", len(entries), len(results))
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
