// Code generated by genlocales.go; DO NOT EDIT.
// Source: github.com/microsoft/winget-cli@5c03e8b3eda726ef8eb70c7df861110c5e1061a8
// Regenerated: 2026-05-07
//
// To regenerate: go run genlocales.go

package main

// wingetLocaleSourceSHA records the upstream winget-cli commit the
// header dictionary was generated from. Surfaced via wintui doctor.
const wingetLocaleSourceSHA = "5c03e8b3eda726ef8eb70c7df861110c5e1061a8"

// wingetHeaderLookup maps a localised column-header word to its semantic
// columnKind. Built from 11 official winget locales.
var wingetHeaderLookup = map[string]columnKind{
	"Available":       colAvailable, // en-US
	"Disponibile":     colAvailable, // it-IT
	"Disponible":      colAvailable, // es-ES
	"Disponível":      colAvailable, // pt-BR
	"Verfügbar":       colAvailable, // de-DE
	"Доступно":        colAvailable, // ru-RU
	"利用可能":            colAvailable, // ja-JP
	"可用":              colAvailable, // zh-CN
	"사용 가능":           colAvailable, // ko-KR
	"ID":              colId,        // de-DE
	"Id":              colId,        // en-US
	"ИД":              colId,        // ru-RU
	"識別碼":             colId,        // zh-TW
	"장치 ID":           colId,        // ko-KR
	"Coincidencia":    colMatch,     // es-ES
	"Correspondance":  colMatch,     // fr-FR
	"Correspondência": colMatch,     // pt-BR
	"Corrispondenza":  colMatch,     // it-IT
	"Match":           colMatch,     // en-US
	"Übereinstimmung": colMatch,     // de-DE
	"Совпадение":      colMatch,     // ru-RU
	"一致":              colMatch,     // ja-JP
	"匹配":              colMatch,     // zh-CN
	"相符":              colMatch,     // zh-TW
	"일치":              colMatch,     // ko-KR
	"Name":            colName,      // en-US
	"Nom":             colName,      // fr-FR
	"Nombre":          colName,      // es-ES
	"Nome":            colName,      // it-IT
	"Имя":             colName,      // ru-RU
	"名前":              colName,      // ja-JP
	"名称":              colName,      // zh-CN
	"名稱":              colName,      // zh-TW
	"이름":              colName,      // ko-KR
	"Origem":          colSource,    // pt-BR
	"Origen":          colSource,    // es-ES
	"Origine":         colSource,    // it-IT
	"Quelle":          colSource,    // de-DE
	"Source":          colSource,    // en-US
	"Источник":        colSource,    // ru-RU
	"ソース":             colSource,    // ja-JP
	"來源":              colSource,    // zh-TW
	"源":               colSource,    // zh-CN
	"원본":              colSource,    // ko-KR
	"Version":         colVersion,   // en-US
	"Versione":        colVersion,   // it-IT
	"Versión":         colVersion,   // es-ES
	"Versão":          colVersion,   // pt-BR
	"Версия":          colVersion,   // ru-RU
	"バージョン":           colVersion,   // ja-JP
	"版本":              colVersion,   // zh-CN
	"버전":              colVersion,   // ko-KR
}

// wingetLocaleCoverage lists the locales the dictionary was generated
// against. Used by wintui doctor for diagnostics.
var wingetLocaleCoverage = []string{
	"en-US",
	"de-DE",
	"es-ES",
	"fr-FR",
	"it-IT",
	"ja-JP",
	"ko-KR",
	"pt-BR",
	"ru-RU",
	"zh-CN",
	"zh-TW",
}
